setwd("E:/D/wanglab/hMeDIP-seq/workdata/")
library(pheatmap)
PT1<-read.table("PT1_peaks.xls.variant_function_table.txt")
head(PT1)
PT2<-read.table("PT2_peaks.xls.variant_function_table.txt")
MT2<-read.table("MT2_peaks.xls.variant_function_table.txt")
DC1<-read.table("DC1_peaks.xls.variant_function_table.txt")
PT<-merge(PT1,PT2,by=intersect(names(PT1)[1],names(PT2)[1]))
MT<-merge(MT2,DC1,by=intersect(names(MT2)[1],names(DC1)[1]))
PT_MT<-merge(PT,MT,by=intersect(names(PT)[1],names(MT)[1]))
write.table(PT_MT,file="Xiaoyi_exonic.txt",sep = "\t",quote = F)
pheatmap(PT_MT,scale="row",cluster_cols = F,show_rownames = F,border=FALSE,fontsize = 12,angle_col = 0)
