B<-1000
n<-length(gmVol)
resamples<-matrix(sample(gmVol,
                         n*B,
                         replace=TRUE),
                  B,n)
medians<-apply(resamples,1,median)
sd(medians)
quantile(median,c(0.025,0.975))
library(bootstrap)
gmVol
data(gmVol)
library(boot)
stat<-b=function(x,i){median(x[i])}
boot.out<-boot(data=gmVol,
               statistic=stat,
               R=1000)
boot.ci(boot.out)